### ISSUE TITLE
Request: Instruction on how to use this

### ISSUE THREAD

**Issue by Vulpovile** [jbatistareis/wmo#1]
This looks really cool and impressive and also confusing,
I've been looking for a library like this for ages, however I can't figure out how to use it

**Comment by jbatistareis** [comment]
Documentation is something that i have been putting aside because im focusing on making it work, but you're right, i guess it is really due time
I will definitely update the readme and make a simple console project showing how to use it in a few days

**Comment by Vulpovile** [comment]
Makes sense, but if others know how to use it they can also provide bug information and contribute code so you might be able to make it work even faster

**Comment by jbatistareis** [comment]
I create some Javadoc comments and updated the README with an example, it should clarify a lot.
Things will get a lot easier to work with when i finish MIDI support.

**Comment by jbatistareis** [comment]
Closing issue
