### ISSUE TITLE
Question about polyphonic FM

### ISSUE THREAD

**Issue by Vulpovile** [jbatistareis/wmo#2]
I am trying to create three instruments and play them like this:
![image](https://user-images.githubusercontent.com/19483545/114294837-ba824600-9a90-11eb-9616-0f3e4c55ed18.png)
however, this creates a really bad whine. what is the preferred way of doing this, if there is one?

**Comment by jbatistareis** [comment]
Yes, theres a specific way of doing this
What i call ByteFrame, ShortFrame, and FloatFrame, are convertions of the actual PCM audio data point made to be sent to an audio output
If you want to play multiple instruments, first you have to grab the PCM data from each instrument, sum them up, and then create a "ByteFrame":

```Java
final byte[] frame = new byte[4];

while (running) {
    double sample = 0;

    // this will probably result in a very loud sound, you will need to reduce the volume of the instruments
    // or just multiply the final result by about 0.8, or less
    sample += instrument.getSample();
    sample += instrument2.getSample();
    sample += instrument3.getSample();

    sample *= MathFunctions.SIGNED_16_BIT_MAX; // this is done because a sample is a normalized double, and an audio frame is a signed 16bit integer

    MathFunctions.primitiveTo16bit(true, frame, 0, (int) sample); // L
    MathFunctions.primitiveTo16bit(true, frame, 2, (int) sample); // R
    dataLine.write(frame, 0, 4);
}
```

**Comment by Vulpovile** [comment]
I found there is a mixer class, does this do the same?

**Comment by jbatistareis** [comment]
Yes, it does
This shows you how long i don't work on this project! 😄 
I will go back to it in the near future

**Comment by Vulpovile** [comment]
I know the feeling XD
